name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-midnight
title: pat25bk.github.io
description: [A short description of your site's purpose]
